# .github/workflows/discord-embed.yml
name: Discord embed ping

on:
  push:
    branches: [ main ]          # ← zmień, jeśli używasz innej gałęzi

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ pobierz kod, żeby git diff działał
      - uses: actions/checkout@v4

      # 2️⃣ policz i zbuduj listę zmienionych plików
      - name: Collect changed files
        id: diff
        run: |
          ALL=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }})
          LIST=$(echo "$ALL" | head -n 15 | paste -sd '\n' -)         # 15 pierwszych
          COUNT=$(echo "$ALL" | wc -l)
          echo "list=$LIST"   >> $GITHUB_OUTPUT
          echo "count=$COUNT" >> $GITHUB_OUTPUT

      # 3️⃣ wyślij embed do Discorda
      - name: Send Discord embed
        env:
          WEBHOOK_URL:   ${{ secrets.DISCORD_WEBHOOK }}
          REPO:          ${{ github.repository }}
          BRANCH:        ${{ github.ref_name }}
          ACTOR:         ${{ github.actor }}
          SHA:           ${{ github.sha }}
          COMMIT_URL:    ${{ github.event.head_commit.url }}
          COMMIT_MSG:    ${{ github.event.head_commit.message }}
          FILE_LIST:     ${{ steps.diff.outputs.list }}
          FILE_COUNT:    ${{ steps.diff.outputs.count }}
        run: |
          # Kolor „Discord blurple” w zapisie dziesiętnym: 5814783
          jq -n \
            --arg content "@everyone" \
            --arg title   "Push ➜ $REPO [$BRANCH]" \
            --arg desc    "**$ACTOR** wypchnął commit [`${SHA:0:7}`]($COMMIT_URL)" \
            --arg msg     "$COMMIT_MSG" \
            --arg files   "$FILE_LIST" \
            --arg count   "$FILE_COUNT" \
            --argjson color 5814783 \
            '{
               content: $content,
               embeds: [{
                 title: $title,
                 description: ($desc + "\n\n" + $msg),
                 color: $color,
                 fields: [{
                   name: ("Zmodyfikowane pliki (" + $count + ")"),
                   value: ( $files != "" ? $files : " — brak zmian —" ),
                   inline: false
                 }],
                 footer: { text: "GitHub → Discord Action" },
                 timestamp: (now | strftime("%Y-%m-%dT%H:%M:%S%z"))
               }]
             }' \
          | curl -H "Content-Type: application/json" -d @- "$WEBHOOK_URL"
