name: Discord embed ping

on:
  push:
    branches: [ main ]          # ← zmień, jeśli używasz innej gałęzi

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣  Klon repo z co najmniej dwoma commitami (potrzebne do git diff)
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2          # 0 = cała historia; 2 jest szybsze i wystarcza

    # 2️⃣  (opcjonalnie) doinstaluj jq, jeśli runner kiedyś by go nie miał
    - name: Ensure jq is present
      run: sudo apt-get update && sudo apt-get install -y jq

    # 3️⃣  Zbierz listę zmienionych plików
    - name: Collect changed files
      id: diff
      run: |
        BEFORE="${{ github.event.before }}"
        AFTER="${{ github.event.after }}"

        # Jeśli to pierwszy push (BEFORE = 0000...), zrób diff tylko względem AFTER
        if [[ "$BEFORE" == "0000000000000000000000000000000000000000" ]]; then
          ALL=$(git diff --name-only "$AFTER")
        else
          ALL=$(git diff --name-only "$BEFORE" "$AFTER")
        fi

        LIST=$(echo "$ALL" | head -n 15 | paste -sd '\n' -)
        COUNT=$(echo "$ALL" | wc -l)

        {
          echo 'list<<EOF'
          echo "$LIST"
          echo 'EOF'
          echo "count=$COUNT"
        } >> "$GITHUB_OUTPUT"

    # 4️⃣  Wyślij embed do Discorda
    - name: Send Discord embed
      env:
        WEBHOOK_URL:  ${{ secrets.DISCORD_WEBHOOK }}
        REPO:         ${{ github.repository }}
        BRANCH:       ${{ github.ref_name }}
        ACTOR:        ${{ github.actor }}
        SHA:          ${{ github.sha }}
        COMMIT_URL:   ${{ github.event.head_commit.url }}
        COMMIT_MSG:   ${{ github.event.head_commit.message }}
        FILE_LIST:    ${{ steps.diff.outputs.list }}
        FILE_COUNT:   ${{ steps.diff.outputs.count }}
      run: |
        set -euo pipefail

        [[ -z "$WEBHOOK_URL" ]] && {
          echo "::error:: Brak sekretu DISCORD_WEBHOOK"; exit 1; }

        ### 1. Przytnij commit message (pierwsza linia, max 256 znaków)
        COMMIT_TITLE=$(echo "$COMMIT_MSG" | head -n1 | head -c256)

        ### 2. Zrób blok z plikami (max 10 linii + licznik)
        if [[ -z "$FILE_LIST" ]]; then
          FILES_BLOCK="(brak zmian)"
        else
          FILES_BLOCK=$(echo "$FILE_LIST" | head -n10)
          (( FILE_COUNT > 10 )) && \
            FILES_BLOCK="${FILES_BLOCK}\n…i $((FILE_COUNT-10)) więcej"
        fi
        FILES_BLOCK="\`\`\`\n${FILES_BLOCK}\n\`\`\`"

        ### 3. JSON-escape dwóch pól (samymi cudzysłowami)
        esc() { python3 -c 'import json,sys; print(json.dumps(sys.stdin.read())[1:-1])'; }
        ESC_COMMIT=$(printf '%s' "$COMMIT_TITLE" | esc)
        ESC_FILES=$(printf '%s' "$FILES_BLOCK"  | esc)

        ### 4. Zbuduj payload heredokiem
        read -r -d '' PAYLOAD <<EOF
{
  "content": "@everyone",
  "embeds": [{
    "title": "Push → $REPO [$BRANCH]",
    "url": "$COMMIT_URL",
    "color": 5814783,
    "author": {
      "name": "$ACTOR",
      "url": "https://github.com/$ACTOR",
      "icon_url": "https://github.com/$ACTOR.png?size=40"
    },
    "fields": [
      { "name": "Commit",           "value": "$ESC_COMMIT", "inline": false },
      { "name": "Pliki ($FILE_COUNT)", "value": "$ESC_FILES", "inline": false }
    ],
    "footer": { "text": "SHA ${SHA:0:7}" },
    "timestamp": "$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
  }]
}
EOF

        ### 5. Wyślij i sprawdź kod HTTP
        CODE=$(curl -sSL -o /dev/null -w '%{http_code}' \
                 -H "Content-Type: application/json" \
                 -d "$PAYLOAD" "$WEBHOOK_URL")
        echo "Discord HTTP $CODE"
        [[ "$CODE" -ne 204 ]] && exit 1
