name: discord-embed-ping
on:
  push:
    branches: [ main ]          # ← zmień, jeżeli trzeba

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with: { fetch-depth: 2 }

    # 1️⃣  Budujemy opis + blok plików
    - id: vars
      shell: bash
      run: |
        set -euo pipefail
        before='${{ github.event.before }}'
        after='${{ github.event.after }}'

        # lista zmienionych plików
        if [[ "$before" == 0000000000000000000000000000000000000000 ]]; then
          files=$(git diff --name-only "$after")
        else
          files=$(git diff --name-only "$before" "$after")
        fi
        count=$(printf '%s\n' "$files" | wc -l)
        short=$(printf '%s\n' "$files" | head -n10)

        # blok code + ewentualny „…i X więcej”
        block="(brak zmian)"
        if [[ -n "$short" ]]; then
          block='```'"$short"'```'
          (( count > 10 )) && block+="\n…i $((count-10)) więcej"
        fi

        first=$(printf '%s' "${{ github.event.head_commit.message }}" \
                | head -n1 | head -c256)

        echo "TITLE=$first"         >> "$GITHUB_OUTPUT"
        echo "FILES=$block"         >> "$GITHUB_OUTPUT"
        echo "COUNT=$count"         >> "$GITHUB_OUTPUT"

    # 2️⃣  Wysyłka embedem (v7 to najnowsze stabilne wydanie)
    - name: Post to Discord
      uses: tsickert/discord-webhook@v7.0.0
      with:
        webhook-url:   ${{ secrets.DISCORD_WEBHOOK }}
        content:       "@everyone"                       # ping
        username:      "GitHub Actions"
        avatar-url:    "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"

        # --- embed ---
        embed-title:        "Push → ${{ github.repository }} [${{ github.ref_name }}]"
        embed-url:          "${{ github.event.head_commit.url }}"
        embed-color:        5814783                      # blurple
        embed-author-name:  "${{ github.actor }}"
        embed-author-url:   "https://github.com/${{ github.actor }}"
        embed-author-icon-url: "https://github.com/${{ github.actor }}.png?size=40"
        embed-description: |
          **${{ steps.vars.outputs.TITLE }}**

          ${{ steps.vars.outputs.FILES }}
